---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sa-platform-postgresql
  namespace: sa-p5
spec:
  encryptedData:
    password: AgCOVdoitU4bBuzqx9DE1Pg1Pfa2dFsmtfjl7OgJv7cV7yco9AFWGpYZt5e31sDeojlD+w49qIsMRXMTMSYffjg90G0O7gBU1IiXtXR6/zQQPYJ8lwiIue8y5KNJzWDw5TZM/R/vv+mGuttCG/l610hUJ96YucPWwoojqK3yLvJdKzfFB8NA72xl1VG6QE3i4s9NUsA73bQc+kJ4m1uDbr+frY/cQx6UVim6SBR5zF/P9LuPvMWjtiNA5RD3G3aILhYZhTDR5r+tEMaH6EUoa5+f78wW4dLMTAvDl89x3WuhyO56NMnKXKU+mJuJjS+HkGU+gNvRluP7/bwZWS4zk+buwObiweOanPV/YgP+B/n9CzxgSIuY97UwCs4ajj7kGliTOcNOLwfyv5n7vOq4On4bFYCgya7b7owx4ef0WXEd8DktJZG1eLclsfLie3u2FnSXw5YXhIZJ9I82tSNSLtyOj3b1l7mOPCcIgHd4o0qw2mXtfF6V0JYFBtq3fhHIdTgkbvTW6M6PD9BWrs+qZOEbcfETL06DNUtUJ0pWiPJvn3sZb2XTnFTdYv3PeiVzEda2xqiJgOf5aB53gMbmn0875gRM/3YPGlz3TqGVjZxAkDCuStKJwbBAGEDX+8ognfu5TrrO3ilD2nN1a+3DoHf+YwN5NVGeWKwqFfwGKvu3iP1+55QJ2H7mavlOAHpBpguCuWIM4PuoWU9Wv0ABk+adqEf0qu+qjHXSrHD+/MxYncM8I/Izq1RpbyJJcak=
    postgres-password: AgCyX1yptH/5p4xUh6UNa2c/w1bVVjDu4vBzolnRUo6MlkKjV7bqBwT589YClfc67vALaw1k+W6hlGMVq9tNYUqpNVBW4L2rBke+05D3ihUEcaAt9e2SSWOpkEZ3rnSTeZnM6Bh8xjdcJImaXApDiwBWib2UuzgtMo/xVBrefcb80Prnv0ds3GwbMsS9hsoqjUQXieDjgFrNCy6/Czjw7L/5wj3iVIdkSyDCDKcU+frQlWMzZFdAMFcGhxO55nmPc662BFrgphfOeypmCCqhYnwaOXegafF5CSelk/twiqo+hEJ3VSO3NDhHjMfLBawmddIRLunThKhN6RJlq+LxQbBP6Nl4OY69gDRgA5YiIM1EuM+9VUR58TK5R/sVpFtcER++RvQLlzwaertyxkuVTUQQw8GwOvRDcE8Ig3kG2XhiDfALDbl6uPT7C8o3wKWtML8/gHst6G2NsA2731UASom5igc7tS3OQ39eJ8bFSmK2kY+wILdaeTHdjreurSX7AtS2UgNS+D1GkkW+Z+e8ZrdOd6BkvoPX8WSOsKXM5SXMz78qfey5aB++G2U4HUkZck8ngJY1YExkh5y5/kZ4dwtNELgm/XNlxqmD5xY6DSsOY6yFYRMqiMYKYECD65+lDc6kRHuzHZx1e8VGy9ac3Sgg/kYjVAGWgLVW/JRABg65euow9Ura2i8JqTjxMCCWcdj40qmNq7KwHkzL
  template:
    metadata:
      name: sa-platform-postgresql
      namespace: sa-p5
