---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sa-platform-postgresql
  namespace: sa-p5
spec:
  encryptedData:
    password: AgACY042LjrRIiGrIONYwbisMgi+NdFGIEeluaWivQ3E7rNFrJ4zm02BczBcZvs2lN/GleperMee8fjcg+m8uQpMfGwNQZRlZerjicijeb/wH7bExyzop8NHVFHASLNX4zxV5uMPgQWBTfaR8VYH8rw55uIVUSjqO1SAfsflvawHmN/Q6besesdM6zIFDnTqS+QldnJ2ruVFmCtLR9BEN8eerRsT0Y60Sw3/mlQFgw/pW+CBh2TPj1l2OWrFjXtNezt5ruwNretdcjN4efs7sR/LvMtx3khCeSGQ7UD2sSPpUJjjaCgd/YzwP+QvZD6WUVjCjmTehbFwv5CBum9lTUtLYLr1fd2IOzqzBdAUsodWXoHWMovJDhZVHN+k6JM0uhZP1pyROIeaXNEcClyj2/MA5cek+0KwNSIc8wsW/q5LVWKlzHPLaGFRkEJBWcRIAtL1P/ymiLOooIoznDDWpRNDJyqubDi5W78J7LXfAtDg1bEhSBWZ/gIy5Pc6BRIqqjEH1gJY/24zqyQ7f34k2RouYbqpz+voHzKPfg8NtHUKU9jrjMn2Vqwk1vU/uTPp+oywprxnoPt5ABqYCDZXQ0bMGlV2VXFOcVd0V1phIW8fs56DNk69YT0o4WgvjwQo7LOFf5ZUShGpwj+DDcci3TrBOnjwdixGxb18r7SDDJS3n8TfwG2Ke1EkJuyE2G80xcvKFF421tem0+zajfXBC5yDm+mlL/MatK71UUU9whmg+5qd/1JSOE2sjH+Z7eA=
    postgres-password: AgCD4rfkVm36KZ2jnqUxRN1XoIszk+rrQIoy40DCrV3A2Q7LXrp4bmUMr8GtQloFodgntCCwZEKpHbryUqgFH2mTlYhKv6bRwHHdY5Qr3r08J/jPm8Y7Hlvt+H8CBVhA8/9ImLMuMEmQUHfLOqRoF6+gg0cZhHDcbJ/I5Z/zqVF/MTyNUfz4aNIo9JvrsvzoYeTMXTPLN71AYj/iR5hVj6/DMDzqTJCtkOQJuxbxowdk8d8V2N6dzw5GslUCu8QlkncvXfMAJE9UpWeq+Y1l1Azyui0ozftf81q6M2S+beGzqVQ9SwviAVPeMkHw0Uf/6z7YgPS3nJgR0JaRhJ0EX43141XzTAhzEQoqVd9KxN5kqWhl9hk93Ty28FTKJf0f7aIUYWOo4TywD3fR5NQbpKvs4Bsrxp2y4DqxFwNQoERM0tRKtfeA07fn0eagvaj40+WrzYdV1IWNhw6g/uQAdCWpN8D7Crt13GnD3Xw8tiStU8XVpcEoivsgNLzthKltLJpquGe6iTjPgIX/6yvvVl3+pgRZC9XmiBngDSCK2GVUmw7i5G8qQHkitO+gm8/CRJv4AMcsWHxlHkRlgThUDWNeHKT1MtjjpfurbfUN5Hq+hh2ur81z577FOGNDvj7SadpzxUuW9yteQE8rAd1wQItRQ/DSQCyutfL8e3QBKLa1fhM0iL6pIcNBGMJGdRNJIg51dGsftuvYU906
  template:
    metadata:
      name: sa-platform-postgresql
      namespace: sa-p5
