---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sa-platform-rabbitmq
  namespace: sa-p5
spec:
  encryptedData:
    rabbitmq-erlang-cookie: AgC4bkjyh1YLSwCTzPkXUt6ayLs5QoXRM2waq1DrBH5qiEJlGA4BPHC3VQa52dBYBK1TOHHpo2UdjmbgdpAJtAiFDjZQFeE+xa6nRrP7JAFq9OFwGhrzbdCfZNAlZldVXzTW+dfCZIwojbjZuuxmyTBCEXnW/lygxmCUSJRs6OML7IzezWF198MGj/7osnAwGTPEhipTMZ7v13EZ4vW3rzSxJVYxpwu97TW96IcLqRxGGqU91bfbUs5Kh26ZNNPJdO9QFhedn4UK/ryky4NBEPudjlfAU8hgtDWQgxs/sjmCLAyITWq6kG7z3n7eBxP8og2Db4ZFwCHJTyweJQp96qHUe4dyVJS6S4yXM1z7wZgWkCYSbRe0JjUVk928+3mvEWQQTfyfDHlILqvVQBjLH7hshjFibD1rIQ6ku7klCl6CJQVNavDUXSRQvikpDHsJQnsLvgZU/KyA2QvD7u5nFVx0qumS5e2pLqiZ2iAQzjaq9Y0X9WRPjFvhokUv09HCn45atIelOUIkVTbgTEz9PmgcICVP0rxVpEmZg1pmbBdNHqFVFbcwyC0vUIOWPGhOfkFRX9PVAWKLaP0oOLOfFlctigSnMo92Bk0ve2cItHCs5MItN51LdJM4pEyGHeiLB9oQjGoL2klli2LZSFtBUJCa66+eFFaRIHrC2urtSD2wU+JbwBfpRwTyw0wnUWDTBWTeRFF+tiaJG9I0+ydcJsdEtdL07NTOXWgvjONkNc+haQ==
    rabbitmq-password: AgDQ7kM+Q+VY/UezCNPOElRZzFOBlR2AbhwTg5076hcjCTrDtK9yiUnJ0oQBCnMlRHAgWw5Oax6g8Y1bIsG3VEzjd1By8EtL6P07vfFHWSFRHrwa0nPHJ/MQGmMGbLI5aTdD1NVdqMBlNi3PiCQtkGp0VgJ50Jut7fGeu6i1jXged3oxxMqOgcooBmLDu2h5zTnRmiGZjssMc/WS4C/pkcxhJBOKHQMxM3a8MVuLMT4OMfB8n1ql6d1Cp/nMqwaMNGwo79cmP4BE7Dl5EHbO+/FvY/i/qLBQQJ98vPeFWYXg0Fcvuz+jRh0ecPUad0E1rh1CMv8nk+7cOrXzIwnMdA6Sax/sRmR5UHSPQ6eRbvP1pjUzudvHY8EIxMc7chxduu4UVDartLMar8duesXuxB14j0n15sQZDv20f8lAJQX1bcQj+ALOhsOmc0qo0zHhLLp14boIuzL4GrjmMDg36THixQ1r3D8EYN2g7m/Gxiw5hlVkVb4M4o5Kz2v1p371IIFPThWNvFdGIIkM4SFLWCvNF3Wkj5EhxA2KxuFk3EcrATb06nVT8VnYZB0cPHxW0SX4RCycvR+bjLxiHScPUoPyfh4xbrCROKyoY5Zru2p9cgLsYNef7qw8gNXMU03tXhybb/pv7c9blFrtNqGdbBBIZC28XrAqrNaXHvpgUFYN4GCR5ChPPrZif2WAvqCXs1qDwAqJJoQ01E23zeg8Wq/6
  template:
    metadata:
      name: sa-platform-rabbitmq
      namespace: sa-p5
