---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sa-platform-rabbitmq
  namespace: sa-p5
spec:
  encryptedData:
    rabbitmq-erlang-cookie: AgBpulpJF4lS1sJfZwvgnvLtfxM/o4S6WKvv6d8o/PX+SE1UAlqgfRhrafx1/ViOo65qq6MmBFbt6uhcWWfH6VTQWx8kMMEkMGyNQijZSpnnEIHxPIDWmGpcedmcUOG+kD0FZLsJsVx/gYwIwY5u9VT5QMsfQElkhiTWIdGrQ0BZkc9ZMAHMhoXOVZ3wASJdaiNFOxARp+zb3ijVdCGZo1KDcwZ9SqetkJ1BAoOvkM8T7Aq0ApYxDoU48HJkt3pH++29oOUs0zMuftUBmC5k3xqiVu/vH4tlYdOy3ZkcBqFzRW13cHlhGA9j7h1s9Tox6N634IJje35cBcOzgxxwHHzudTRhpHfVvebjAADjOW4K3qxbyM7Qn/CS3aDkBo6dRnrwwo6TW4WvaRuhv5It7zofXldGgDwyS54Z9jsn949VCSUAcIrgNZ3m0jB0OWpa6sW8IQJROhOGExlYg7kD8RuAZBvNJ0O0BDGhmuhE39ZpVYxprD+a1PhcqyTbQOfRYnGGtyvg+C94ph8BHM4S2nutxLL3KnEdDWyM3PB9+XpALScK1wVtD23kLAUXT4qaTef/6pvUxV774W4d5RlMDkG8T6km9ltZZC0jUDxs3DhFhvDifPNCn7s2cSHQgqBzB4Xosu97ty5NislBnkdmaDz2iLtsb57o6XbdvYFsXeqKK/IWjZxyqDEsc2voKBsdFNlqIvY7YtmSj7+3TXCZ7hGMA7m/1d+MKoMCmrUV9NTdSw==
    rabbitmq-password: AgDhHW9amiqaydmBPYIPwFmZBgAI9aPvHWLVVcqDbJHiyKHsiwOVfTWv9DZjQCURI0SXu+JxWHB4BQOjgvLPI/7lkuOoDGrv/8bujoGFV2MPh3tCbNj68y9M5FBWgoSIX1PS/ppRMJowp3tjTFCMe1IziQLlKMAb1MKOD9OzOA6iAyZgVNLl64VUiYnGwNo3GWTdxgVe3DiPtQ7Q3PeuelII/DSAx2lXodfCfghMLwYNn58zlyjRARikA8EuJfAtMq5uj92eMnQgJC9cVPvN7ad7xcDN0Ia/bhb8QWc0GqqibR4g2rofvtBe+sjOYbJTp9MVlMjO4Zd8qIpVVsM0jrm+GxXBQFH4Qho7hhWJaFRwu4xCebT63kkenXjFRudaL5NgrhY/ZGnX2dgxdgDtu0WzwpR/BFtGX6QkI1UhfYTGcCPCGrIP6Wllu+AZHbCq5jHR/hg6M+owcTa78ZDsWzzooeexSEq+o278+zmaN4Bg7JsH2KyjJkk2YFGw1pD20r7GkRGbX8eetdN8mZK2C/VkopAsYQPpMtAqV2pF9A9swnV1p8NAizo+x0QSAxbp8ZmudCzV998GM8/dAexFSW9l6QVbE9gRuXygtdDFs/SEhc6LpCINGltjcsBQ3jQlkNTRum3KsFjpH81jY6EJ6n5OrxxweGlzCp+roBFFv4+BFQ339OEk64Nb+8EG8BE5NgJXZ3Xu94uyVIGxV27sTFhC
  template:
    metadata:
      name: sa-platform-rabbitmq
      namespace: sa-p5
